[package]
name = "mystr"
version = "0.1.0"
authors = ["juanillo"]
edition = "2018"

[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`
# The release profile, used for `cargo build --release`

[profile.release]
opt-level = 3
debug = false

[dependencies]
